apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopdeploy

resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - mongodb-statefulset.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml
  - resource-quota.yaml

labels:
  - pairs:
      app: shopdeploy
      managed-by: kustomize
    includeSelectors: false
